//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crud_CampeonatoFutebol.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CampeonatoFutebolEntities : DbContext
    {
        public CampeonatoFutebolEntities()
            : base("name=CampeonatoFutebolEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Campeonato> Campeonato { get; set; }
        public DbSet<Estadio> Estadio { get; set; }
        public DbSet<Estado> Estado { get; set; }
        public DbSet<Jogador> Jogador { get; set; }
        public DbSet<PosicaoJogador> PosicaoJogador { get; set; }
        public DbSet<Tecnico> Tecnico { get; set; }
        public DbSet<Time> Time { get; set; }
        public DbSet<TimeCampeonato> TimeCampeonato { get; set; }
        public DbSet<TipoEvento> TipoEvento { get; set; }
        public DbSet<Transferencias> Transferencias { get; set; }
        public DbSet<EventoPartida> EventoPartida { get; set; }
        public DbSet<ResultadoPartida> ResultadoPartida { get; set; }
        public DbSet<Partida> Partida { get; set; }
    }
}
