//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crud_CampeonatoFutebol.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Campeonato
    {
        public Campeonato()
        {
            this.TimeCampeonato = new HashSet<TimeCampeonato>();
        }
    
        public int CampeonatoId { get; set; }
        public string Nome { get; set; }
        public bool Status { get; set; }
        public Nullable<System.DateTime> DataInicio { get; set; }
        public Nullable<System.DateTime> DataFim { get; set; }
        public System.DateTime DataAlteracao { get; set; }
    
        public virtual ICollection<TimeCampeonato> TimeCampeonato { get; set; }
    }
}
