//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crud_CampeonatoFutebol.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estadio
    {
        public Estadio()
        {
            this.Partida = new HashSet<Partida>();
        }
    
        public int EstadioId { get; set; }
        public string Nome { get; set; }
        public decimal Capacidade { get; set; }
        public Nullable<int> EstadoId { get; set; }
        public System.DateTime DataAlteracao { get; set; }
    
        public virtual Estado Estado { get; set; }
        public virtual ICollection<Partida> Partida { get; set; }
    }
}
