//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crud_CampeonatoFutebol.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estado
    {
        public Estado()
        {
            this.Estadio = new HashSet<Estadio>();
            this.Time = new HashSet<Time>();
        }
    
        public int EstadoId { get; set; }
        public string Nome { get; set; }
        public string UF { get; set; }
        public Nullable<int> IBGE { get; set; }
        public Nullable<int> Pais { get; set; }
    
        public virtual ICollection<Estadio> Estadio { get; set; }
        public virtual ICollection<Time> Time { get; set; }
    }
}
