//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crud_CampeonatoFutebol.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partida
    {
        public Partida()
        {
            this.EventoPartida = new HashSet<EventoPartida>();
        }
    
        public int PartidaId { get; set; }
        public int TimeCampeonato1Id { get; set; }
        public System.DateTime DataInicio { get; set; }
        public Nullable<int> ResultadoPartidaId { get; set; }
        public int EstadioId { get; set; }
        public System.DateTime DataAlteracao { get; set; }
        public int TimeCampeonato2Id { get; set; }
    
        public virtual Estadio Estadio { get; set; }
        public virtual ICollection<EventoPartida> EventoPartida { get; set; }
        public virtual ResultadoPartida ResultadoPartida { get; set; }
        public virtual TimeCampeonato TimeCampeonato { get; set; }
        public virtual TimeCampeonato TimeCampeonato1 { get; set; }
    }
}
