//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crud_CampeonatoFutebol.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PosicaoJogador
    {
        public PosicaoJogador()
        {
            this.Jogador = new HashSet<Jogador>();
        }
    
        public int PosicaoJogadorId { get; set; }
        public string Nome { get; set; }
    
        public virtual ICollection<Jogador> Jogador { get; set; }
    }
}
