//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crud_CampeonatoFutebol.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tecnico
    {
        public int TecnicoId { get; set; }
        public string Nome { get; set; }
        public System.DateTime DataNascimento { get; set; }
        public int TimeAtualId { get; set; }
        public System.DateTime DataAlteracao { get; set; }
    
        public virtual Time Time { get; set; }
    }
}
