//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crud_CampeonatoFutebol.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeCampeonato
    {
        public TimeCampeonato()
        {
            this.Partida = new HashSet<Partida>();
            this.Partida1 = new HashSet<Partida>();
        }
    
        public int TimeCampeonatoId { get; set; }
        public int CampeonatoId { get; set; }
        public int TimeId { get; set; }
        public System.DateTime DataAlteracao { get; set; }
    
        public virtual Campeonato Campeonato { get; set; }
        public virtual Time Time { get; set; }
        public virtual ICollection<Partida> Partida { get; set; }
        public virtual ICollection<Partida> Partida1 { get; set; }
    }
}
