//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crud_CampeonatoFutebol.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Time
    {
        public Time()
        {
            this.Jogador = new HashSet<Jogador>();
            this.Tecnico = new HashSet<Tecnico>();
            this.TimeCampeonato = new HashSet<TimeCampeonato>();
            this.Transferencias = new HashSet<Transferencias>();
            this.Transferencias1 = new HashSet<Transferencias>();
        }
    
        public int TimeId { get; set; }
        public string Nome { get; set; }
        public Nullable<int> EstadoId { get; set; }
        public System.DateTime DataAlteracao { get; set; }
    
        public virtual Estado Estado { get; set; }
        public virtual ICollection<Jogador> Jogador { get; set; }
        public virtual ICollection<Tecnico> Tecnico { get; set; }
        public virtual ICollection<TimeCampeonato> TimeCampeonato { get; set; }
        public virtual ICollection<Transferencias> Transferencias { get; set; }
        public virtual ICollection<Transferencias> Transferencias1 { get; set; }
    }
}
