//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crud_CampeonatoFutebol.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoEvento
    {
        public TipoEvento()
        {
            this.EventoPartida = new HashSet<EventoPartida>();
        }
    
        public int TipoEventoId { get; set; }
        public string NomeEvento { get; set; }
    
        public virtual ICollection<EventoPartida> EventoPartida { get; set; }
    }
}
