//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crud_CampeonatoFutebol.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transferencias
    {
        public int TransferenciasId { get; set; }
        public int JogadorId { get; set; }
        public int TimeOrigemId { get; set; }
        public int TImeDestinoId { get; set; }
        public Nullable<decimal> Valor { get; set; }
        public System.DateTime Data { get; set; }
        public System.DateTime DataAlteracao { get; set; }
    
        public virtual Jogador Jogador { get; set; }
        public virtual Time Time { get; set; }
        public virtual Time Time1 { get; set; }
    }
}
