name: build and deploy

on: 
  push:
    branches: [master]

jobs:
  build:
   name: build
   runs-on: windows-latest

   steps:     
    - uses: actions/checkout@v3
      
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Setup NuGet.exe for use with actions
      uses: NuGet/setup-nuget@v1.1.1
    
    - name: Create Build Directory
      run: mkdir ${{github.workspace}}\_build\
      
    - name: Restore NuGet packages
      run: nuget locals all -clear; nuget restore CampeonatoFutebol.sln -PackagesDirectory packages
      
    - name: Build the solution
      run: msbuild ${{github.workspace}}\CampeonatoFutebol.sln -verbosity:minimal -t:rebuild -property:Configuration=Release /p:WebPublishMethod=FileSystem /p:DeployOnBuild=true /p:PublishUrl="../_build"
    
    - name: Upload artifact    
    - uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: ${{github.workspace}}\_build\       
        
  deploy:
    needs: build
    name: Copy WebPublish files to remote server
    runs-on: self-hosted
    
    steps:
      - name: Download artifact
      - uses: actions/download-artifact@v3
        with:
          name: my-artifact
      
      - name: Extraindo
        run: Expand Archive -Path 'D:\a\CampeonatoFutebolRestAPI\CampeonatoFutebolRestAPI\Crud_CampeonatoFutebol\obj\Release\Package\Crud_CampeonatoFutebol.zip' -DestinationPath 'C:\Users\bianc\Downloads\Temp' -Force
        shell: pwsh
