name: build and deploy

on: 
  push:
    branches: [master]

jobs:
  build:
   name: build
   runs-on: windows-latest

   steps:     
    - uses: actions/checkout@v3
      
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Setup NuGet.exe for use with actions
      uses: NuGet/setup-nuget@v1.1.1
    
    - name: Create Build Directory
      run: mkdir ${{github.workspace}}\_build\
      
    - name: Restore NuGet packages
      run: nuget locals all -clear; nuget restore CampeonatoFutebol.sln -PackagesDirectory packages
      
    - name: Build the solution
      run: msbuild CampeonatoFutebol.sln -verbosity:minimal -t:rebuild -property:Configuration=Release /p:PublishProfile=IISProfile.pubxml /p:WebPublishMethod=FileSystem /p:DeployOnBuild=true /p:DeployDefaultTarget=WebPublish /p:PublishUrl="../_build"
    
    - uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: ${{github.workspace}}\_build\       
        
  deploy:
    needs: Build
    name: Copy WebPublish files to remote server
    runs-on: self-hosted
    
    steps:
      - name: Run PowerShell Remove-Item 
        run: Remove-Item ${{github.workspace}}\_build\ -Force -Recurse

      - uses: actions/download-artifact@master
        with:
          name: my-artifact
          path: ${{github.workspace}}\_build\

      - name: Run PowerShell Copy-Item
        run: |
            $psversiontable;
            iisreset /stop
            Copy-Item -Path ${{github.workspace}}\_build\* c:/websites/dev.${{github.event.repository.name}} -Recurse -Force
            iisreset /stop
